---
title: "Houston Restaurant Weeks, 2019"
resource_files:
- hrw_menus.csv
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    theme: cerulean
    vertical_layout: scroll
---

```{r}
knitr::opts_chunk$set(fig.width=8, fig.height=5, echo=FALSE, warning=FALSE, message=FALSE, error = FALSE, fig.pos='center', cache=FALSE, progress=TRUE)

options(shiny.error =  function() {
    stop("")
  },
  shiny.reactlog = TRUE,
  shiny.sanitize.errors = FALSE)

# Get packages ------------------------------------------------------------
library(tidyverse)
library(shiny)
library(flexdashboard)
library(DT)
library(leaflet)
```


```{r}
all_menus <- read_csv("hrw_menus.csv") 
```


```{r}
filt_menus <- reactive({
  if(input$name == "All restaurants"){
    all_menus
  } else{
    all_menus %>% 
      dplyr::filter(name %in% input$name) 
  }
})

```

```{r}
offerings <- reactive({
  filt_menus() %>%
    group_by(restaurant_url, name, latitude, longitude, address, phone) %>%
    summarise(meals = n_distinct(meal_idx),
              course = n_distinct(course_num),
              items = n_distinct(item)) %>% 
    arrange(desc(items)) %>% 
    ungroup() %>% 
    mutate(url_ = paste0("<a href='", restaurant_url,"'>",name,"</a>"),
           content = paste(url_, address, phone, 
                           paste("# of meals =", meals), 
                           paste("# of courses =", course),
                           paste("# of items =", items),
                           sep = "<br/>")) 
    })


```


Home
=================================================================
Column {.sidebar}
-----------------------------------------------------------------------
```{r filters}
selectizeInput("name", 
               "Restaurant Name",         
               choices = c("All restaurants", unique(all_menus$name)),
               multiple = TRUE,
               width = '100%',
               selected = "All restaurants")

```

row
---------------------------------------------------------------
### Houston Restaurant Weeks headcount

```{r}
renderValueBox({
    valueBox(value = n_distinct(all_menus$url), 
           caption = "<b># of Restaurants offering HRW and parsed</b>", 
           icon = "fa-cutlery", 
           color = "#77AF43")

})
```

Column {data-height=1000, data-width=800, style="height:100pc;" .tabset .tabset-fade}
-----------------------------------------------------------------------

### HRW maps
```{r geolocate,fig.width=12, fig.height=8}
output$hrw_map <- renderLeaflet({
  offerings() %>%
    leaflet(., options = leafletOptions(
                zoomControl = TRUE)) %>%
    addTiles() %>%
    addMarkers(lat = ~latitude, lng = ~longitude, 
               popup = ~content) 
})
  
leafletOutput('hrw_map', height = 400)    
```


Search restaurant details
=================================================================

Column {data-height=10000, data-width=1000, style="height:100pc;" .tabset .tabset-fade}
-----------------------------------------------------------------------

### Table view of HRW
```{r}
DT::renderDataTable(filt_menus() %>% 
                      select(-latitude, -longitude, -name), 
                      extensions = "Responsive", 
                      escape = FALSE,
                      filter = list(position = 'top', clear = TRUE, plain = FALSE),
                      options = list(
                      columnDefs = list(list(className = 'dt-center', targets = 5)),
                                    searchHighlight = TRUE,
                                    pageLength = 20,
                                    fixedHeader = TRUE,
                                    fixedColumns = TRUE,
                                    autoWidth = TRUE,
                                    ordering = TRUE))

```

